FROM node:20

WORKDIR /app

# Copy package.json files first for caching npm install
COPY package*.json /app
RUN npm install

# Copy the rest of the application code
COPY . /app

# Ensure the dev server stays running
CMD ["npm", "run", "dev"]
