import { FaSearch, FaShoppingBag, FaSignInAlt, FaUser, FaSignOutAlt, FaTrash, FaExpandAlt, FaStar, FaRegStar, FaPlus, FaChartBar, FaChartLine, FaChartPie, FaStopwatch, FaGamepad } from "react-icons/fa";
import { VscError } from "react-icons/vsc";
import { BiArrowBack, BiSolidCoupon } from "react-icons/bi";
import { FcGoogle } from "react-icons/fc";
import { MdError, MdDiscount } from "react-icons/md";
import { FaArrowLeftLong, FaArrowRightLong, FaFacebookF, FaInstagram, FaLinkedinIn, FaTwitter, FaAnglesDown, FaHeadset } from "react-icons/fa6";
import { FiEdit } from "react-icons/fi";
import { AiFillFileText, AiOutlineSortAscending, AiOutlineSortDescending } from "react-icons/ai";
import { HiMenuAlt4 } from "react-icons/hi";
import { IoIosPeople } from "react-icons/io";
import { RiCoupon3Fill, RiDashboardFill, RiShoppingBag3Fill } from "react-icons/ri";
import { TbTruckDelivery } from "react-icons/tb";
import { LuShieldCheck } from "react-icons/lu";
export { FaSearch, FaShoppingBag, FaSignInAlt, FaUser, FaSignOutAlt, VscError, FaTrash, BiArrowBack, FcGoogle, MdError, BiSolidCoupon, MdDiscount, FaExpandAlt, FaStar, FaRegStar, FaArrowLeftLong,  FaArrowRightLong, FiEdit, FaFacebookF, FaInstagram, FaLinkedinIn, FaTwitter, FaPlus, AiFillFileText, FaChartBar, FaChartLine, FaChartPie, FaStopwatch, FaGamepad, HiMenuAlt4, IoIosPeople, RiCoupon3Fill, RiDashboardFill, RiShoppingBag3Fill, AiOutlineSortAscending, AiOutlineSortDescending, FaAnglesDown, FaHeadset, TbTruckDelivery, LuShieldCheck };
